### ISSUE TITLE
Double Check Login

### ISSUE THREAD

**Issue by cestes-csumb** [DannyJacoby/CST438_P3_SP21#20]

**Comment by Smash-the-Keyboard** [comment]
The login bug occurred because the Login Activity was adding "none" to preferences instead of the user's id, so the comparison of mUserId and "none" was always true.

The initial fix indirectly avoided this by comparing references and probably because of Java's String pool. The comparison of the default value "none" returned by mPrefs.getString() before login with a "none" literal was actually comparing two of the same String reference and therefore false, while comparing the "none" retrieved from preferences (set by the Login Activity) to the "none" literal in the Landing Activity returned true since they were different String references.

Replacing the "none" literals with null values and adding the user's id to preferences in the Login Activity appears to have resolved the issue.
